[keywords]
patterns = [
  "html", "head", "body", "div", "span", "p", "a", "img", "script", "style", "link", "meta", "title", "h1", "h2", "h3", "h4", "h5", "h6", "ul", "ol", "li", "table", "tr", "td", "th", "form", "input", "button", "textarea", "select", "option"
]
color = "86, 156, 214"

[types]
patterns = []
color = "255, 255, 255"

[comments]
patterns = [
  "<!--[\\s\\S]*?-->"
]
color = "106, 153, 85"

[strings]
patterns = [
  "=\"([^\"\\\\]|\\\\.)*\"", "='([^'\\\\]|\\\\.)*'"
]
color = "206, 145, 120"

[numbers]
patterns = []
color = "255, 255, 255"

[operators]
patterns = [
  "<", ">", "/", "="
]
color = "212, 212, 212"

[methods]
patterns = []
color = "255, 255, 255"

