[keywords]
patterns = ["true", "false"]
color = "86, 156, 214"

[types]
patterns = ["null"]
color = "220, 50, 47"

[comments]
patterns = []
color = "255, 255, 255"

[strings]
patterns = ["\"([^\"\\\\]|\\\\.)*\""]
color = "206, 145, 120"

[numbers]
patterns = ["\\b\\d+(\\.\\d+)?([eE][+-]?\\d+)?\\b"]
color = "181, 206, 168"

[operators]
patterns = ["\\{", "\\}", "\\[", "\\]", ":", ","]
color = "212, 212, 212"

[methods]
patterns = []
color = "255, 255, 255"
