[keywords]
patterns = [
  "#", "##", "###", "####", "#####", "######", "**", "*", "_", "`", "```", ">", "-", "\\+", "1\\.", "\\[", "\\]", "\\(", "\\)"
]
color = "86, 156, 214"

[types]
patterns = []
color = "255, 255, 255"

[comments]
patterns = []
color = "255, 255, 255"

[strings]
patterns = [
  "\\[([^\\]]+)\\]"
]
color = "206, 145, 120"

[numbers]
patterns = []
color = "255, 255, 255"

[operators]
patterns = [
  "#", "\\*", "_", "`", ">", "-", "\\+", "\\[", "\\]", "\\(", "\\)", "=", "-"
]
color = "212, 212, 212"

[methods]
patterns = []
color = "255, 255, 255"

