[keywords]
patterns = []
color = "255, 255, 255"

[types]
patterns = []
color = "255, 255, 255"

[comments]
patterns = [
  "<!--[\\s\\S]*?-->"
]
color = "106, 153, 85"

[strings]
patterns = [
  "=\"([^\"\\\\]|\\\\.)*\"", "='([^'\\\\]|\\\\.)*'"
]
color = "206, 145, 120"

[numbers]
patterns = []
color = "255, 255, 255"

[operators]
patterns = [
  "<", ">", "/", "=", "\\?", "!"
]
color = "212, 212, 212"

[methods]
patterns = []
color = "255, 255, 255"

